# Sourceable shell hook for the shared claude-workflow gateway daemon.
# Installed into the current shell's rc file by:
# scripts/claude-workflow-daemon.sh install-shell
#
# Ensures the daemon is running (non-blocking) and exports its published env
# so plain, resumed, and background Claude Code sessions can use the configured
# route when their user/project/organization settings do not override these
# environment values. The claude-workflow launcher supplies a higher-precedence
# per-session settings layer when deterministic routing is required.
case $- in
  *x*) _CLAUDE_WORKFLOW_GATEWAY_HOOK_XTRACE=1; set +x ;;
  *) _CLAUDE_WORKFLOW_GATEWAY_HOOK_XTRACE=0 ;;
esac
_claude_workflow_gateway_restore_environment() {
  case $- in
    *x*) _CLAUDE_WORKFLOW_GATEWAY_RESTORE_XTRACE=1; set +x ;;
    *) _CLAUDE_WORKFLOW_GATEWAY_RESTORE_XTRACE=0 ;;
  esac
  case $- in
    *a*) _CLAUDE_WORKFLOW_GATEWAY_RESTORE_ALLEXPORT=1; set +a ;;
    *) _CLAUDE_WORKFLOW_GATEWAY_RESTORE_ALLEXPORT=0 ;;
  esac
  _CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES="${CLAUDE_WORKFLOW_GATEWAY_MANAGED_ENV_NAMES-}"
  _CLAUDE_WORKFLOW_GATEWAY_MANAGED_SET_NAMES="${CLAUDE_WORKFLOW_GATEWAY_MANAGED_ENV_SET_NAMES-}"
  _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_SET_NAMES="${CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_ENV_SET_NAMES-}"
  _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_EXPORTED_NAMES="${CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_ENV_EXPORTED_NAMES-}"
  while [ -n "$_CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES" ]; do
    case "$_CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES" in
      *" "*)
        _CLAUDE_WORKFLOW_GATEWAY_ENV_NAME="${_CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES%% *}"
        _CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES="${_CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES#* }"
        ;;
      *)
        _CLAUDE_WORKFLOW_GATEWAY_ENV_NAME="$_CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES"
        _CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES=''
        ;;
    esac
    case "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" in
      ''|[0-9]*|*[!A-Za-z0-9_]*) continue ;;
    esac
    _CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE_NAME="CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE_${_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME}"
    _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_NAME="CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_${_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME}"
    eval "_CLAUDE_WORKFLOW_GATEWAY_CURRENT_SET=\${${_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME}+x}"
    _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED=0
    case " $_CLAUDE_WORKFLOW_GATEWAY_MANAGED_SET_NAMES " in
      *" $_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME "*)
        eval "_CLAUDE_WORKFLOW_GATEWAY_CURRENT_VALUE=\${${_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME}-}"
        eval "_CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE=\${${_CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE_NAME}-}"
        if [ "$_CLAUDE_WORKFLOW_GATEWAY_CURRENT_SET" = x ] &&
          [ "$_CLAUDE_WORKFLOW_GATEWAY_CURRENT_VALUE" = "$_CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE" ]; then
          if _CLAUDE_WORKFLOW_GATEWAY_ENV_DECLARATION="$(typeset -p "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null)"; then
            case "$_CLAUDE_WORKFLOW_GATEWAY_ENV_DECLARATION" in
              export\ *) _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED=1 ;;
              declare\ *|typeset\ *)
                _CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES="${_CLAUDE_WORKFLOW_GATEWAY_ENV_DECLARATION#* }"
                _CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES="${_CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES%% *}"
                case "$_CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES" in -*x*) _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED=1 ;; esac
                ;;
            esac
          else
            # Shells without typeset cannot distinguish the export attribute.
            _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED=1
          fi
          unset _CLAUDE_WORKFLOW_GATEWAY_ENV_DECLARATION 2>/dev/null || :
          unset _CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES 2>/dev/null || :
        fi
        ;;
      *)
        if [ "$_CLAUDE_WORKFLOW_GATEWAY_CURRENT_SET" != x ]; then
          _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED=1
        fi
        ;;
    esac
    if [ "$_CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED" = 1 ]; then
      case " $_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_SET_NAMES " in
        *" $_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME "*)
          eval "_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_SET=\${${_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_NAME}+x}"
          if [ "$_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_SET" = x ]; then
            eval "_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE=\${${_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_NAME}-}"
            case " $_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_EXPORTED_NAMES " in
              *" $_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME "*)
                eval 'export '"$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME"'="${_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE}"' 2>/dev/null || :
                ;;
              *)
                if [ -n "${BASH_VERSION-}" ]; then
                  export -n "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null || :
                elif [ -n "${ZSH_VERSION-}" ]; then
                  typeset -g +x "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null || :
                else
                  unset "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null || :
                fi
                eval "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME=\${_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE}" 2>/dev/null || :
                ;;
            esac
          else
            unset "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null || :
          fi
          ;;
        *) unset "$_CLAUDE_WORKFLOW_GATEWAY_ENV_NAME" 2>/dev/null || : ;;
      esac
    fi
    unset "$_CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE_NAME" 2>/dev/null || :
    unset "$_CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_NAME" 2>/dev/null || :
  done
  unset CLAUDE_WORKFLOW_GATEWAY_MANAGED_ENV_NAMES 2>/dev/null || :
  unset CLAUDE_WORKFLOW_GATEWAY_MANAGED_ENV_SET_NAMES 2>/dev/null || :
  unset CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_ENV_SET_NAMES 2>/dev/null || :
  unset CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_ENV_EXPORTED_NAMES 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_MANAGED_NAMES _CLAUDE_WORKFLOW_GATEWAY_MANAGED_SET_NAMES 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_SET_NAMES _CLAUDE_WORKFLOW_GATEWAY_ENV_NAME 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_EXPORTED_NAMES 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE_NAME _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_NAME 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_CURRENT_SET _CLAUDE_WORKFLOW_GATEWAY_CURRENT_VALUE 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_ENV_DECLARATION 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_ENV_ATTRIBUTES 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_MANAGED_VALUE _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_VALUE_SET 2>/dev/null || :
  unset _CLAUDE_WORKFLOW_GATEWAY_VALUE_OWNED 2>/dev/null || :
  if [ "$_CLAUDE_WORKFLOW_GATEWAY_RESTORE_ALLEXPORT" = 1 ]; then set -a; fi
  unset _CLAUDE_WORKFLOW_GATEWAY_RESTORE_ALLEXPORT 2>/dev/null || :
  if [ "$_CLAUDE_WORKFLOW_GATEWAY_RESTORE_XTRACE" = 1 ]; then
    unset _CLAUDE_WORKFLOW_GATEWAY_RESTORE_XTRACE 2>/dev/null || :
    set -x
  else
    unset _CLAUDE_WORKFLOW_GATEWAY_RESTORE_XTRACE 2>/dev/null || :
  fi
  return 0
}
_claude_workflow_gateway_restore_environment || :
unset -f _claude_workflow_gateway_restore_environment 2>/dev/null || :

if [ -n "${CLAUDE_WORKFLOW_GATEWAY_MANAGED_AUTH_TOKEN:-}" ]; then
  if [ "${ANTHROPIC_AUTH_TOKEN-}" = "$CLAUDE_WORKFLOW_GATEWAY_MANAGED_AUTH_TOKEN" ]; then
    unset ANTHROPIC_AUTH_TOKEN 2>/dev/null || :
  fi
  if [ "${ANTHROPIC_API_KEY-}" = "$CLAUDE_WORKFLOW_GATEWAY_MANAGED_AUTH_TOKEN" ]; then
    unset ANTHROPIC_API_KEY 2>/dev/null || :
  fi
fi
unset CLAUDE_WORKFLOW_GATEWAY_MANAGED_AUTH_TOKEN 2>/dev/null || :

if [ -n "${CLAUDE_WORKFLOW_GATEWAY_MANAGED_TERMINAL_TITLE:-}" ]; then
  if [ "${CLAUDE_CODE_DISABLE_TERMINAL_TITLE-}" = "$CLAUDE_WORKFLOW_GATEWAY_MANAGED_TERMINAL_TITLE" ]; then
    if [ "${CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_TERMINAL_TITLE_SET-}" = '1' ]; then
      export CLAUDE_CODE_DISABLE_TERMINAL_TITLE="${CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_TERMINAL_TITLE-}" 2>/dev/null || :
    else
      unset CLAUDE_CODE_DISABLE_TERMINAL_TITLE 2>/dev/null || :
    fi
  fi
fi
unset CLAUDE_WORKFLOW_GATEWAY_MANAGED_TERMINAL_TITLE 2>/dev/null || :
unset CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_TERMINAL_TITLE 2>/dev/null || :
unset CLAUDE_WORKFLOW_GATEWAY_PREVIOUS_TERMINAL_TITLE_SET 2>/dev/null || :

if [ "$_CLAUDE_WORKFLOW_GATEWAY_HOOK_XTRACE" = 1 ]; then
  unset _CLAUDE_WORKFLOW_GATEWAY_HOOK_XTRACE 2>/dev/null || :
  set -x
else
  unset _CLAUDE_WORKFLOW_GATEWAY_HOOK_XTRACE 2>/dev/null || :
fi

if [ -n "${BASH_SOURCE:-}" ]; then
  _CLAUDE_WORKFLOW_GATEWAY_SOURCE="${BASH_SOURCE[0]}"
elif [ -n "${ZSH_VERSION:-}" ]; then
  _CLAUDE_WORKFLOW_GATEWAY_SOURCE="$(eval 'printf "%s" "${(%):-%x}"')"
else
  _CLAUDE_WORKFLOW_GATEWAY_SOURCE=""
fi

if ! _CLAUDE_WORKFLOW_GATEWAY_DIR="$(
  cd "$(dirname "$_CLAUDE_WORKFLOW_GATEWAY_SOURCE")" 2>/dev/null && pwd
)"; then
  _CLAUDE_WORKFLOW_GATEWAY_DIR=""
fi
if [ -n "$_CLAUDE_WORKFLOW_GATEWAY_DIR" ] && [ -x "$_CLAUDE_WORKFLOW_GATEWAY_DIR/claude-workflow-daemon.sh" ]; then
  _CLAUDE_WORKFLOW_GATEWAY_MANAGER="$_CLAUDE_WORKFLOW_GATEWAY_DIR/claude-workflow-daemon.sh"
  _CLAUDE_WORKFLOW_GATEWAY_CANONICAL_STATE_DIR="${XDG_STATE_HOME:-${HOME-}/.cache}/claude-workflow"
  _CLAUDE_WORKFLOW_GATEWAY_LEGACY_STATE_DIR="${HOME-}/.cache/ultrathink"
  if [ -n "${CLAUDE_WORKFLOW_GATEWAY_STATE_DIR:-}" ]; then
    _CLAUDE_WORKFLOW_GATEWAY_STATE_DIR="$CLAUDE_WORKFLOW_GATEWAY_STATE_DIR"
  elif [ ! -e "$_CLAUDE_WORKFLOW_GATEWAY_CANONICAL_STATE_DIR" ] && {
    [ -f "$_CLAUDE_WORKFLOW_GATEWAY_LEGACY_STATE_DIR/claude-workflow-gateway.pid" ] ||
      [ -f "$_CLAUDE_WORKFLOW_GATEWAY_LEGACY_STATE_DIR/claude-workflow-gateway.env" ]
  }; then
    _CLAUDE_WORKFLOW_GATEWAY_STATE_DIR="$_CLAUDE_WORKFLOW_GATEWAY_LEGACY_STATE_DIR"
  else
    _CLAUDE_WORKFLOW_GATEWAY_STATE_DIR="$_CLAUDE_WORKFLOW_GATEWAY_CANONICAL_STATE_DIR"
  fi
  _CLAUDE_WORKFLOW_GATEWAY_ENV_FILE="${CLAUDE_WORKFLOW_GATEWAY_ENV_FILE:-$_CLAUDE_WORKFLOW_GATEWAY_STATE_DIR/claude-workflow-gateway.env}"
  if "$_CLAUDE_WORKFLOW_GATEWAY_MANAGER" ensure >/dev/null 2>&1; then
    _CLAUDE_WORKFLOW_GATEWAY_ATTEMPT=0
    while [ "$_CLAUDE_WORKFLOW_GATEWAY_ATTEMPT" -lt 20 ]; do
      if "$_CLAUDE_WORKFLOW_GATEWAY_MANAGER" status >/dev/null 2>&1 && [ -r "$_CLAUDE_WORKFLOW_GATEWAY_ENV_FILE" ]; then
        if . "$_CLAUDE_WORKFLOW_GATEWAY_ENV_FILE"; then
          break
        fi
      fi
      _CLAUDE_WORKFLOW_GATEWAY_ATTEMPT=$((_CLAUDE_WORKFLOW_GATEWAY_ATTEMPT + 1))
      sleep 0.1
    done
  fi
fi
unset _CLAUDE_WORKFLOW_GATEWAY_SOURCE
unset _CLAUDE_WORKFLOW_GATEWAY_DIR
unset _CLAUDE_WORKFLOW_GATEWAY_MANAGER
unset _CLAUDE_WORKFLOW_GATEWAY_CANONICAL_STATE_DIR
unset _CLAUDE_WORKFLOW_GATEWAY_LEGACY_STATE_DIR
unset _CLAUDE_WORKFLOW_GATEWAY_STATE_DIR
unset _CLAUDE_WORKFLOW_GATEWAY_ENV_FILE
unset _CLAUDE_WORKFLOW_GATEWAY_ATTEMPT
